### ISSUE TITLE
Error occurs when reopening a deleted buffer

### ISSUE THREAD

**Issue by yesmeck** [marilari88/twoslash-queries.nvim#17]
<img width="1147" alt="Screenshot 2024-06-19 at 23 13 15" src="https://github.com/marilari88/twoslash-queries.nvim/assets/465125/c0b17456-1a9b-4b6a-b2a6-f8cea5d417d9">

Reproduce steps:

1. Open a TypeScript file.
2. Add a twoslash query under a variable.
3. Delete the buffer with command `:bd`
4. Reopen the file.

**Comment by thenbe** [comment]
Same error also happens if you attempt to re-enable twoslash after disabling it.

Reproduction:

1. Run `EnableTwoslashQueries`
1. Observe twoslash has been enabled.
1. Run `DisableTwoslashQueries`
1. Observe twoslash has been disabled.
1. Run `EnableTwoslashQueries`
1. Observe error message (screenshot in OP).
1. Observe that twoslash is still disabled. The only way to make it work again is to restart nvim.

---

Config:

```lua
		opts = {
			multi_line = true,
			is_enabled = false,
			highlight = 'Type',
		},
```
